export type Country = 'USA' | 'Canada';
export type Region = string; // State or Province
export type Benefit =
  | 'Nutrient & Fertilizer Management'
  | 'Soil Health & Carbon'
  | 'Climate & Drought Resilience'
  | 'Water Quality & Conservation'
  | 'Crop Yield & Vigor'
  | 'On-Farm Trials & Research'
  | 'Specialty Crops';

export interface Grant {
  id: string;
  name: string;
  organization: string;
  country: Country;
  regions: Region[]; // 'All' or specific states/provinces
  isFederal: boolean;
  benefits: Benefit[];
  description: string;
  amount: string;
  deadline: string;
  link: string;
}

export const USA_STATES = [
  'All States', 'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
];

export const CANADA_PROVINCES = [
  'All Provinces', 'Alberta', 'British Columbia', 'Manitoba', 'New Brunswick', 'Newfoundland and Labrador', 'Nova Scotia', 'Ontario', 'Prince Edward Island', 'Quebec', 'Saskatchewan', 'Northwest Territories', 'Nunavut', 'Yukon'
];

const RAW_GRANTS: any[] = [
  // --- USA FEDERAL ---
  {
    id: 'usa-eqip-1',
    name: 'Environmental Quality Incentives Program (EQIP)',
    organization: 'USDA NRCS',
    country: 'USA',
    regions: ['All States'],
    isFederal: true,
    benefits: ['Soil Health', 'Fertilizer Reduction', 'Drought Tolerance'],
    description: 'Provides financial and technical assistance to agricultural producers to address natural resource concerns and deliver environmental benefits. Ideal for integrating biostimulants as part of a nutrient management or soil health enhancement plan.',
    amount: 'Varies by practice',
    deadline: 'Continuous',
    link: 'https://www.nrcs.usda.gov/programs-initiatives/eqip-environmental-quality-incentives',
  },
  {
    id: 'usa-csp-1',
    name: 'Conservation Stewardship Program (CSP)',
    organization: 'USDA NRCS',
    country: 'USA',
    regions: ['All States'],
    isFederal: true,
    benefits: ['Soil Health', 'Drought Tolerance', 'General'],
    description: 'Helps agricultural producers maintain and improve existing conservation systems and adopt additional conservation activities. Using biostimulants can qualify under enhancements for reducing synthetic inputs.',
    amount: 'Up to $200,000 / 5-year contract',
    deadline: 'Continuous',
    link: 'https://www.nrcs.usda.gov/programs-initiatives/csp-conservation-stewardship',
  },
  {
    id: 'usa-sare-1',
    name: 'SARE Farmer/Rancher Grant',
    organization: 'SARE',
    country: 'USA',
    regions: ['All States'],
    isFederal: true,
    benefits: ['Fertilizer Reduction', 'Yield Improvement', 'Stand Improvement', 'General'],
    description: 'Grants aimed at testing new ideas using biostimulants and innovative farming practices to solve agricultural problems and find ways to farm more sustainably.',
    amount: 'Up to $30,000 (individual)',
    deadline: 'Varies by SARE region',
    link: 'https://www.sare.org/grants/farmer-rancher/',
  },
  // --- USA STATE LEVEL ---
  {
    id: 'usa-ca-hsi-1',
    name: 'Healthy Soils Program (HSP)',
    organization: 'CDFA',
    country: 'USA',
    regions: ['California'],
    isFederal: false,
    benefits: ['Soil Health', 'Drought Tolerance', 'Fertilizer Reduction'],
    description: 'Incentives for California farmers to implement conservation management practices that improve soil health, sequester carbon and reduce greenhouse gas emissions.',
    amount: 'Up to $100,000 per project',
    deadline: 'Check CDFA website',
    link: 'https://www.cdfa.ca.gov/oefi/healthysoils/',
  },
  {
    id: 'usa-ia-wqf-1',
    name: 'Water Quality Initiative (WQI)',
    organization: 'Iowa Dept. of Ag',
    country: 'USA',
    regions: ['Iowa'],
    isFederal: false,
    benefits: ['Nitrogen Uptake', 'Fertilizer Reduction'],
    description: 'Provides cost-share for practices that reduce nutrient runoff. Incorporating biologicals and biostimulants to increase nitrogen use efficiency matches nutrient management plans.',
    amount: 'Up to 50% cost-share',
    deadline: 'Rolling',
    link: 'https://cleanwateriowa.org/water-quality-initiative',
  },
  {
    id: 'usa-mn-shfg',
    name: 'Soil Health Financial Assistance Program',
    organization: 'Minnesota Department of Agriculture',
    country: 'USA',
    regions: ['Minnesota'],
    isFederal: false,
    benefits: ['Soil Health', 'Drought Tolerance'],
    description: 'Grants to producers to purchase or retrofit specialized equipment to implement soil health practices. Can include specialized application equipment for liquid biostimulants.',
    amount: 'Up to $50,000',
    deadline: 'Annual',
    link: 'https://www.mda.state.mn.us/environment-sustainability/soil-health-financial-assistance-program',
  },

  // --- CANADA FEDERAL ---
  {
    id: 'can-fed-ofcaf',
    name: 'Agricultural Climate Solutions – On-Farm Climate Action Fund (OFCAF)',
    organization: 'Agriculture and Agri-Food Canada',
    country: 'Canada',
    regions: ['All Provinces'],
    isFederal: true,
    benefits: ['Nitrogen Uptake', 'Fertilizer Reduction', 'Soil Health'],
    description: 'Best national fit. Funds adoption of Beneficial Management Practices (BMPs) in nitrogen management, cover cropping, and rotational grazing.',
    amount: 'Varies',
    deadline: '2025-2028 Delivery',
    link: 'https://agriculture.canada.ca/en/programs/agricultural-climate-solutions-farm-climate-action-fund',
  },
  {
    id: 'can-fed-agriscience',
    name: 'AgriScience Program – Projects',
    organization: 'Agriculture and Agri-Food Canada',
    country: 'Canada',
    regions: ['All Provinces'],
    isFederal: true,
    benefits: ['General'],
    description: 'Best federal fit for partnerships with university, crop group, or applied research farms. Funds pre-commercial applied science/R&D, including climate change and environment priority areas.',
    amount: 'Up to $5M per project',
    deadline: '2023–2028 Framework',
    link: 'https://agriculture.canada.ca/en/programs/agriscience-projects',
  },
  {
    id: 'can-fed-act-adoption',
    name: 'Agricultural Clean Technology Program – Adoption Stream',
    organization: 'Agriculture and Agri-Food Canada',
    country: 'Canada',
    regions: ['All Provinces'],
    isFederal: true,
    benefits: ['Fertilizer Reduction'],
    description: 'Funded commercially available clean technology or equipment upgrades that reduce GHG or fertilizer emissions. (Check if renewed)',
    amount: '$25k–$2M',
    deadline: 'Currently closed (Check for renewal)',
    link: 'https://agriculture.canada.ca/en/programs/agricultural-clean-technology-adoption-stream',
  },
  {
    id: 'can-fed-act-research',
    name: 'Agricultural Clean Technology – Research & Innovation / Accelerator',
    organization: 'Agriculture and Agri-Food Canada',
    country: 'Canada',
    regions: ['All Provinces'],
    isFederal: true,
    benefits: ['General'],
    description: 'Better for validating lignin-derived technology (R&D) rather than purchasing inputs. Runs to March 31, 2028.',
    amount: 'Varies',
    deadline: 'Active until 2028',
    link: 'https://agriculture.canada.ca/en/programs/accelerator',
  },
  {
    id: 'can-fed-agriinnovate',
    name: 'AgriInnovate',
    organization: 'Agriculture and Agri-Food Canada',
    country: 'Canada',
    regions: ['All Provinces'],
    isFederal: true,
    benefits: ['General'],
    description: 'Repayable contribution funding for commercialization, demonstration, or adoption of commercial-ready innovative technologies. Better for businesses than individual farms.',
    amount: 'Varies (Repayable)',
    deadline: 'Currently closed',
    link: 'https://agriculture.canada.ca/en/programs/agriinnovate',
  },
  {
    id: 'can-fed-living-labs',
    name: 'Agricultural Climate Solutions – Living Labs',
    organization: 'Agriculture and Agri-Food Canada',
    country: 'Canada',
    regions: ['All Provinces'],
    isFederal: true,
    benefits: ['Soil Health', 'Drought Tolerance'],
    description: 'Not usually a direct farmer grant, but very relevant for on-farm trials around nitrogen-use, soil-health, fertilization, climate-resilience, and cropping-systems via regional labs.',
    amount: 'Varies (Partnerships)',
    deadline: 'Continuous',
    link: 'https://agriculture.canada.ca/en/environment/climate-change/agricultural-climate-solutions/agricultural-climate-solutions-living-labs',
  },

  // --- CANADA PROVINCIAL (Alberta) ---
  {
    id: 'can-ab-ofcaf-rdar',
    name: 'OFCAF via RDAR',
    organization: 'RDAR',
    country: 'Canada',
    regions: ['Alberta'],
    isFederal: false,
    benefits: ['Nitrogen Uptake', 'Fertilizer Reduction'],
    description: 'Apply under nitrogen management if the project reduces synthetic N and is tied to a nutrient plan, soil testing, enhanced-efficiency N, or precision placement.',
    amount: 'Varies',
    deadline: '2025–2028 Delivery',
    link: 'https://agriculture.canada.ca/en/programs/agricultural-climate-solutions-farm-climate-action-fund',
  },
  {
    id: 'can-ab-efficiency',
    name: 'On-Farm Efficiency Program',
    organization: 'Alberta.ca',
    country: 'Canada',
    regions: ['Alberta'],
    isFederal: false,
    benefits: ['Fertilizer Reduction'],
    description: 'Supports efficient use of agricultural inputs. Better fit for variable-rate fertilizer, sensors, mapping, section control, or application equipment.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.alberta.ca/on-farm-efficiency-program',
  },
  {
    id: 'can-ab-ralp',
    name: 'Resilient Agricultural Landscape Program (RALP)',
    organization: 'Alberta.ca',
    country: 'Canada',
    regions: ['Alberta'],
    isFederal: false,
    benefits: ['Soil Health'],
    description: 'Fits if the project includes soil-health, carbon, perennial cover, or landscape-resilience practices.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.alberta.ca/resilient-agricultural-landscape-program',
  },

  // --- CANADA PROVINCIAL (British Columbia) ---
  {
    id: 'can-bc-ofcaf',
    name: 'Climate Agri-Solutions Fund / OFCAF',
    organization: 'BC Investment Agriculture Foundation',
    country: 'Canada',
    regions: ['British Columbia', 'Yukon'],
    isFederal: false,
    benefits: ['Nitrogen Uptake', 'Soil Health'],
    description: 'Use for nitrogen-management BMPs, cover cropping, or grazing-related climate practices. Delivery via BC IAF.',
    amount: 'Varies',
    deadline: '2025–2028 Delivery',
    link: 'https://agriculture.canada.ca/en/programs/agricultural-climate-solutions-farm-climate-action-fund',
  },
  {
    id: 'can-bc-bmp',
    name: 'BC Beneficial Management Practices Program',
    organization: 'Investment Agriculture Foundation of BC',
    country: 'Canada',
    regions: ['British Columbia'],
    isFederal: false,
    benefits: ['Soil Health', 'Drought Tolerance'],
    description: 'Strong fit if project is around nutrient management, soil carbon, extreme heat, drought, or climate adaptation.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://iafbc.ca/beneficial-management-practices-program/',
  },
  {
    id: 'can-bc-efp',
    name: 'BC Environmental Farm Plan',
    organization: 'Investment Agriculture Foundation of BC',
    country: 'Canada',
    regions: ['British Columbia'],
    isFederal: false,
    benefits: ['General'],
    description: 'Required gateway: Complete or update the EFP first; BC links EFP completion to many BMP funding opportunities.',
    amount: 'Support/Planning',
    deadline: 'Continuous',
    link: 'https://iafbc.ca/environmental-farm-plan/',
  },

  // --- CANADA PROVINCIAL (Saskatchewan) ---
  {
    id: 'can-sk-pwcp-ofcaf',
    name: 'Prairie Watersheds Climate Program (OFCAF)',
    organization: 'Manitoba Association of Watersheds',
    country: 'Canada',
    regions: ['Saskatchewan', 'Manitoba'],
    isFederal: false,
    benefits: ['Nitrogen Uptake', 'Fertilizer Reduction'],
    description: 'Strong fit for nitrogen reduction, nitrogen stabilizers, fertilizer planning, soil testing, and equipment upgrades. Delivers up to 85% cost-share (max $75k).',
    amount: 'Up to $75,000 (85% cost-share)',
    deadline: 'Check website',
    link: 'https://manitobawatersheds.org/prairie-watershed-climate-program',
  },
  {
    id: 'can-sk-adopt',
    name: 'ADOPT — Agriculture Demonstration of Practices and Technologies',
    organization: 'Government of Saskatchewan',
    country: 'Canada',
    regions: ['Saskatchewan'],
    isFederal: false,
    benefits: ['General', 'Yield Improvement'],
    description: 'Best SK-specific route for a replicated local trial. Funds producer groups to test new practices/technologies.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.saskatchewan.ca/business/agriculture-natural-resources-and-industry/agribusiness-farmers-and-ranchers/sustainable-canadian-agricultural-partnership/programs-for-research/ag-demonstration-of-practices-and-technologies',
  },
  {
    id: 'can-sk-ralp',
    name: 'Saskatchewan RALP',
    organization: 'Government of Saskatchewan',
    country: 'Canada',
    regions: ['Saskatchewan'],
    isFederal: false,
    benefits: ['Soil Health', 'General'],
    description: 'Fits projects tied to soil health, water quality, biodiversity, or landscape resilience.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.saskatchewan.ca/business/agriculture-natural-resources-and-industry/agribusiness-farmers-and-ranchers/sustainable-canadian-agricultural-partnership/programs-for-farmers-and-ranchers/resilient-agricultural-landscapes-program',
  },
  {
    id: 'can-sk-water',
    name: 'Farm and Ranch Water Infrastructure Program',
    organization: 'Government of Saskatchewan',
    country: 'Canada',
    regions: ['Saskatchewan'],
    isFederal: false,
    benefits: ['Drought Tolerance'],
    description: 'Useful if the drought-resilience angle includes water supply or irrigation. Not a direct biostimulant program.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.saskatchewan.ca/business/agriculture-natural-resources-and-industry/agribusiness-farmers-and-ranchers/sustainable-canadian-agricultural-partnership/programs-for-farmers-and-ranchers/farm-and-ranch-water-infrastructure-program',
  },

  // --- CANADA PROVINCIAL (Manitoba) ---
  {
    id: 'can-mb-sam',
    name: 'Sustainable Agriculture Manitoba — Cropland Management',
    organization: 'Government of Manitoba',
    country: 'Canada',
    regions: ['Manitoba'],
    isFederal: false,
    benefits: ['Fertilizer Reduction', 'Nitrogen Uptake'],
    description: 'Strong for low-disturbance fertilizer placement, variable-rate application, sensors, section control, and nitrogen-use-efficiency improvements.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.gov.mb.ca/asset_library/en/scap/documents/sam-cropland-management-guide-v04.0.pdf',
  },
  {
    id: 'can-mb-ralp',
    name: 'Manitoba RALP',
    organization: 'Government of Manitoba',
    country: 'Canada',
    regions: ['Manitoba'],
    isFederal: false,
    benefits: ['Soil Health'],
    description: 'More useful if you add perennial cover, grassland, carbon-sequestration, or landscape-resilience practices.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.gov.mb.ca/scap/index.html',
  },

  // --- CANADA PROVINCIAL (Ontario) ---
  {
    id: 'can-on-ofcaf-core',
    name: 'OFCAF via OSCIA — Core BMP',
    organization: 'Ontario Soil and Crop Association',
    country: 'Canada',
    regions: ['Ontario'],
    isFederal: false,
    benefits: ['Nitrogen Uptake', 'Soil Health'],
    description: 'Fits nitrogen-management BMPs, cover cropping, and rotational grazing.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.ontariosoilcrop.org/ontario-on-farm-climate-action-fund/',
  },
  {
    id: 'can-on-ofcaf-innovative',
    name: 'OFCAF Innovative BMP',
    organization: 'Ontario Soil and Crop Association',
    country: 'Canada',
    regions: ['Ontario'],
    isFederal: false,
    benefits: ['Soil Health', 'Fertilizer Reduction'],
    description: 'OSCIA lists Innovative BMP cost-share for biological inoculants and biochar as soil amendments (intake closed currently).',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.ontariosoilcrop.org/ontario-on-farm-climate-action-fund/',
  },
  {
    id: 'can-on-ofcaf-knowledge',
    name: 'OFCAF Knowledge Sharing Event',
    organization: 'OSCIA-Delivered',
    country: 'Canada',
    regions: ['Ontario'],
    isFederal: false,
    benefits: ['General'],
    description: 'Useful if you want to host a field day, webinar, workshop, or on-farm demonstration around nitrogen reduction and trial results.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://programguides.ontariosoilcrop.org/program/knowledge-transfer-and-translation-activity-support-for-bmp-adoption/',
  },
  {
    id: 'can-on-oscia-local',
    name: 'OSCIA Local/Regional Grants',
    organization: 'Ontario Soil and Crop Association',
    country: 'Canada',
    regions: ['Ontario'],
    isFederal: false,
    benefits: ['General'],
    description: 'Local/regional OSCIA associations can access funding for communication, demonstrations, and on-farm applied research, including in-field trials.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.ontariosoilcrop.org/oscia-grants/',
  },
  {
    id: 'can-on-ralp',
    name: 'Ontario RALP',
    organization: 'Ontario Soil and Crop Association',
    country: 'Canada',
    regions: ['Ontario'],
    isFederal: false,
    benefits: ['Soil Health'],
    description: 'Supports Ontario farmers with projects that make land more productive and resilient while reducing GHGs.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.ontariosoilcrop.org/resilient-agricultural-landscape-program/',
  },

  // --- CANADA PROVINCIAL (Quebec) ---
  {
    id: 'can-qc-agrisolutions',
    name: 'Agrisolutions climat / OFCAF via UPA',
    organization: 'Union des producteurs agricoles',
    country: 'Canada',
    regions: ['Quebec'],
    isFederal: false,
    benefits: ['Fertilizer Reduction', 'Nitrogen Uptake'],
    description: 'Strong fit for mineral nitrogen reduction, cover crops, nitrification/urease inhibitors, and other nitrogen-efficiency practices.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.upa.qc.ca/agrisolutions-climat',
  },
  {
    id: 'can-qc-primevert',
    name: 'Prime-Vert — Volet 1.3 on-farm trials',
    organization: 'Gouvernement du Québec',
    country: 'Canada',
    regions: ['Quebec'],
    isFederal: false,
    benefits: ['General'],
    description: 'One of the best provincial fits for trials. Supports on-farm trials supervised by an advisor, with control plots, replication, and eligible agri-environmental practices.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.quebec.ca/agriculture-environnement-et-ressources-naturelles/agriculture/aide-financiere/prime-vert',
  },
  {
    id: 'can-qc-retribution',
    name: 'Rétribution des pratiques agroenvironnementales',
    organization: 'Gouvernement du Québec',
    country: 'Canada',
    regions: ['Quebec'],
    isFederal: false,
    benefits: ['Fertilizer Reduction'],
    description: 'Pays for eligible agri-environmental practices, including improved fertilizer management and reduction of mineral nitrogen fertilizer.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.quebec.ca/agriculture-environnement-et-ressources-naturelles/agriculture/aide-financiere/retribution-agroenvironnementale',
  },
  {
    id: 'can-qc-services',
    name: 'Programme services-conseils',
    organization: 'Gouvernement du Québec',
    country: 'Canada',
    regions: ['Quebec'],
    isFederal: false,
    benefits: ['General'],
    description: 'Use this to fund advisor time for the nutrient plan, trial protocol, fertilizer-reduction plan, and agronomic reporting.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.quebec.ca/agriculture-environnement-et-ressources-naturelles/agriculture/aide-financiere/programme-services-conseils',
  },
  {
    id: 'can-qc-innovation',
    name: 'Programme Innovation bioalimentaire',
    organization: 'Gouvernement du Québec',
    country: 'Canada',
    regions: ['Quebec'],
    isFederal: false,
    benefits: ['General'],
    description: 'Fit if the project is run with a producer group, research body, or innovation partner to validate or transfer the lignin-biostimulant practice.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.quebec.ca/agriculture-environnement-et-ressources-naturelles/agriculture/aide-financiere/programme-innovation-bioalimentaire',
  },

  // --- CANADA PROVINCIAL (New Brunswick) ---
  {
    id: 'can-nb-ofcaf',
    name: 'OFCAF via NBSCIA',
    organization: 'NBSCIA',
    country: 'Canada',
    regions: ['New Brunswick'],
    isFederal: false,
    benefits: ['Soil Health', 'Nitrogen Uptake'],
    description: 'Fits nitrogen management, cover cropping, rotational grazing, soil health, and climate BMP adoption.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.nbscia.ca/ofcaf-program-registration/',
  },
  {
    id: 'can-nb-bmp',
    name: 'Beneficial Management Practices Program',
    organization: 'Government of New Brunswick',
    country: 'Canada',
    regions: ['New Brunswick'],
    isFederal: false,
    benefits: ['Fertilizer Reduction', 'General'],
    description: 'Strong fit for precision farming applications that reduce synthetic fertilizer use, such as GPS, variable-rate fertilizer, mapping, section control, cameras.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www2.gnb.ca/content/dam/gnb/Departments/10/pdf/Agriculture/AgriculturePrograms-ProgrammeAgriculture/program-guidelines-lignes-directrices-du-programme/bmp-program-guidelines.pdf',
  },
  {
    id: 'can-nb-agroenv',
    name: 'Agro-Environmental Services',
    organization: 'Government of New Brunswick',
    country: 'Canada',
    regions: ['New Brunswick'],
    isFederal: false,
    benefits: ['General'],
    description: 'Likely useful for planning/advisory work around nutrient management, environmental risk, and BMP design.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www2.gnb.ca/content/gnb/en/departments/10/agriculture/content/agriculture_programs.html',
  },
  {
    id: 'can-nb-research',
    name: 'Enabling Agricultural Research and Innovation',
    organization: 'Government of New Brunswick',
    country: 'Canada',
    regions: ['New Brunswick'],
    isFederal: false,
    benefits: ['General'],
    description: 'Best NB fit if you want to test the biostimulant through a formal applied research or innovation project.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www2.gnb.ca/content/gnb/en/departments/10/agriculture/content/agriculture_programs.html',
  },
  {
    id: 'can-nb-ralp',
    name: 'NB RALP',
    organization: 'Government of New Brunswick',
    country: 'Canada',
    regions: ['New Brunswick'],
    isFederal: false,
    benefits: ['Soil Health'],
    description: 'Better fit if the project includes soil health, perennial cover, biodiversity, or landscape resilience.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www2.gnb.ca/content/gnb/en/departments/10/agriculture/content/agriculture_programs.html',
  },

  // --- CANADA PROVINCIAL (Nova Scotia) ---
  {
    id: 'can-ns-ofcaf',
    name: 'OFCAF via Perennia',
    organization: 'OFCAF',
    country: 'Canada',
    regions: ['Nova Scotia'],
    isFederal: false,
    benefits: ['Soil Health', 'Nitrogen Uptake'],
    description: 'Fits nitrogen management, cover cropping, grazing, soil health, and climate BMP adoption.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://ofcaf.perennia.ca/',
  },
  {
    id: 'can-ns-stewardship',
    name: 'Environmental Stewardship and Climate Change Program',
    organization: 'Government of Nova Scotia',
    country: 'Canada',
    regions: ['Nova Scotia'],
    isFederal: false,
    benefits: ['General'],
    description: 'Supports producers adopting priority BMPs that reduce environmental risk, reduce GHGs, and adapt to climate impacts.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://novascotia.ca/programs/environmental-stewardship-and-climate-change/',
  },
  {
    id: 'can-ns-trials',
    name: 'Agricultural Research and Innovation Program — On-Farm Trials',
    organization: 'Government of Nova Scotia',
    country: 'Canada',
    regions: ['Nova Scotia'],
    isFederal: false,
    benefits: ['General'],
    description: 'Good fit for testing a lignin-derived biostimulant with replicated farm trials. Investigates productivity, competitiveness, and sustainability.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://novascotia.ca/programs/agricultural-research-innovation/ari-program-guidelines.pdf',
  },
  {
    id: 'can-ns-tech-adoption',
    name: 'Technology Adoption Program',
    organization: 'Government of Nova Scotia',
    country: 'Canada',
    regions: ['Nova Scotia'],
    isFederal: false,
    benefits: ['General'],
    description: 'Fit if the project includes new equipment or technology for automation, efficiency, productivity, or precision agriculture.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://novascotia.ca/programs/technology-adoption/',
  },

  // --- CANADA PROVINCIAL (PEI) ---
  {
    id: 'can-pei-ofcaf',
    name: 'OFCAF via PEI Federation of Agriculture',
    organization: 'PEI Federation of Agriculture',
    country: 'Canada',
    regions: ['Prince Edward Island'],
    isFederal: false,
    benefits: ['Nitrogen Uptake'],
    description: 'Fits nitrogen management, cover cropping, and grazing BMPs that reduce GHGs or sequester carbon.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://peifa.ca/ofcaf/',
  },
  {
    id: 'can-pei-stewardship',
    name: 'Agriculture Stewardship Program',
    organization: 'Government of Prince Edward Island',
    country: 'Canada',
    regions: ['Prince Edward Island'],
    isFederal: false,
    benefits: ['Soil Health', 'General'],
    description: 'Strong fit for soil health, nutrient management, climate mitigation/adaptation, water-use efficiency, and agri-environmental demonstration trials.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.princeedwardisland.ca/en/information/agriculture/agriculture-stewardship-program',
  },
  {
    id: 'can-pei-research',
    name: 'Agriculture Research and Innovation Program',
    organization: 'Government of Prince Edward Island',
    country: 'Canada',
    regions: ['Prince Edward Island'],
    isFederal: false,
    benefits: ['General'],
    description: 'Good fit for farm-level applied research, crop trials, clean tech, monitoring equipment, lab fees, and adoption of new BMPs.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.princeedwardisland.ca/en/information/agriculture/agriculture-research-and-innovation-program-0',
  },
  {
    id: 'can-pei-alus',
    name: 'ALUS PEI',
    organization: 'Government of Prince Edward Island',
    country: 'Canada',
    regions: ['Prince Edward Island'],
    isFederal: false,
    benefits: ['Soil Health'],
    description: 'Better for land-use changes: perennial cover, buffers, pollinator habitat, agroforestry, and carbon sequestration.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.princeedwardisland.ca/en/information/agriculture/alternative-land-use-services-alus-program',
  },
  {
    id: 'can-pei-resiliency',
    name: 'Agriculture Resiliency / Perennial Crop Development',
    organization: 'Government of Prince Edward Island',
    country: 'Canada',
    regions: ['Prince Edward Island'],
    isFederal: false,
    benefits: ['Drought Tolerance', 'Soil Health'],
    description: 'Useful if the drought/heat-resilience angle includes perennial cropping systems, extreme-weather adaptation, or soil-carbon practices.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.princeedwardisland.ca/en/information/agriculture/agriculture-resiliency-program',
  },

  // --- CANADA PROVINCIAL (NL) ---
  {
    id: 'can-nl-ofcaf',
    name: 'OFCAF-NL',
    organization: 'Newfoundland and Labrador Federation of Agriculture',
    country: 'Canada',
    regions: ['Newfoundland and Labrador'],
    isFederal: false,
    benefits: ['Nitrogen Uptake', 'Soil Health'],
    description: 'Current OFCAF-NL streams include improving nitrogen management, cover cropping, and rotational grazing.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.acsnl.ca/ofcaf-nl',
  },
  {
    id: 'can-nl-escc',
    name: 'Environmental Sustainability and Climate Change / BMPs',
    organization: 'Government of NL',
    country: 'Canada',
    regions: ['Newfoundland and Labrador'],
    isFederal: false,
    benefits: ['Fertilizer Reduction'],
    description: 'Strong fit for precision farming that reduces synthetic fertilizer use, fertigation, BMP equipment, environmental protection, and climate adaptation.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.gov.nl.ca/fal/files/Sustainable-CAP-Program-Guide-September-2025.pdf',
  },
  {
    id: 'can-nl-ralp',
    name: 'Newfoundland and Labrador RALP',
    organization: 'Government of NL',
    country: 'Canada',
    regions: ['Newfoundland and Labrador'],
    isFederal: false,
    benefits: ['Soil Health'],
    description: 'Fits land-use and management practices that improve soil, water, biodiversity, landscape resilience, and climate adaptation.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.gov.nl.ca/releases/2026/fal/0112n01/',
  },
  {
    id: 'can-nl-research',
    name: 'Agriculture Research Program',
    organization: 'Government of NL',
    country: 'Canada',
    regions: ['Newfoundland and Labrador'],
    isFederal: false,
    benefits: ['General'],
    description: 'Fit for evaluating innovative technologies, products, or processes, including environmental impacts, climate adaptation, and GHG reduction.',
    amount: 'Varies',
    deadline: 'Check website',
    link: 'https://www.gov.nl.ca/fal/files/Sustainable-CAP-Program-Guide-September-2025.pdf',
  },
  {
    id: 'can-nl-living-lab',
    name: 'Newfoundland and Labrador Living Lab',
    organization: 'Agriculture and Agri-Food Canada',
    country: 'Canada',
    regions: ['Newfoundland and Labrador'],
    isFederal: true,
    benefits: ['Soil Health', 'Fertilizer Reduction'],
    description: 'Good fit for collaborative testing: includes soil nutrient/fertilizer management, soil health, climate change mitigation, and farmer-led field testing.',
    amount: 'Varies (Partnerships)',
    deadline: 'Continuous',
    link: 'https://agriculture.canada.ca/en/agri-info/newfoundland-and-labrador-farmers-researchers-and-partners-working-closer-ever-tackle-climate-change',
  },

  // --- ADDITIONAL USA GRANTS ---
  {
    id: 'usa-fed-rcpp',
    name: 'Regional Conservation Partnership Program (RCPP)',
    organization: 'USDA NRCS',
    country: 'USA',
    regions: ['All States'],
    isFederal: true,
    benefits: ['Soil Health', 'Fertilizer Reduction'],
    description: 'Use if your farm is inside a watershed/soil-health/nutrient-management partnership area. Participate through a selected RCPP partner project.',
    amount: 'Varies',
    deadline: 'Continuous',
    link: 'https://www.nrcs.usda.gov/programs-initiatives/regional-conservation-partnership-program',
  },
  {
    id: 'usa-fed-cig',
    name: 'Conservation Innovation Grants (CIG) / On-Farm Trials',
    organization: 'USDA NRCS',
    country: 'USA',
    regions: ['All States'],
    isFederal: true,
    benefits: ['General'],
    description: 'Best route if working with a university, crop group, or agronomist network. Supports innovative approaches on working lands.',
    amount: 'Varies',
    deadline: 'Annual',
    link: 'https://www.nrcs.usda.gov/programs-initiatives/conservation-innovation-grants',
  },
  {
    id: 'usa-fed-regenerative',
    name: 'Regenerative Pilot Program',
    organization: 'USDA NRCS',
    country: 'USA',
    regions: ['All States'],
    isFederal: true,
    benefits: ['Soil Health', 'Drought Tolerance'],
    description: 'Very good fit if framed as whole-farm soil, water, and natural vitality improvement. Uses EQIP & CSP funds.',
    amount: 'Varies',
    deadline: 'Unknown (New 2026)',
    link: 'https://www.usda.gov/about-usda/news/press-releases/2025/12/10/usda-launches-new-regenerative-pilot-program-lower-farmer-production-costs-and-advance-maha-agenda',
  },
  {
    id: 'usa-fed-scbgp',
    name: 'Specialty Crop Block Grant Program (SCBGP)',
    organization: 'USDA AMS',
    country: 'USA',
    regions: ['All States'],
    isFederal: true,
    benefits: ['Yield Improvement', 'Stand Improvement'],
    description: 'Fit for fruit, vegetables, tree nuts, dried fruit, nursery, greenhouse, horticulture, or floriculture. Farmers apply through state processes.',
    amount: 'Varies',
    deadline: 'Through June 2026',
    link: 'https://www.ams.usda.gov/services/grants/scbgp',
  },
  {
    id: 'usa-fed-nifa',
    name: 'AFRI / Strengthening Agricultural Systems',
    organization: 'USDA NIFA',
    country: 'USA',
    regions: ['All States'],
    isFederal: true,
    benefits: ['General'],
    description: 'Good if the project becomes a university-led or multi-partner research/extension project on nitrogen-use efficiency, plant health, or drought stress.',
    amount: 'Varies',
    deadline: 'Annual Cycles',
    link: 'https://www.nifa.usda.gov/grants/programs/agriculture-food-research-initiative',
  },

  // State specific
  { id: 'usa-al-cip', name: 'Conservation Incentive Program (CIP)', organization: 'Alabama Soil & Water Conservation Committee', country: 'USA', regions: ['Alabama'], isFederal: false, benefits: ['Fertilizer Reduction', 'Soil Health'], description: 'Frame as a water-quality / erosion / nutrient-management BMP with reduced N and soil-health measurements.', amount: 'Varies', deadline: 'Check Local', link: 'https://alabamasoilandwater.gov/cip/?utm_source=chatgpt.com' },
  { id: 'usa-ak-scbg', name: 'Alaska Specialty Crop Block Grant', organization: 'Alaska DNR', country: 'USA', regions: ['Alaska'], isFederal: false, benefits: ['Yield Improvement'], description: 'Best for specialty crops, greenhouse crops, soil moisture monitoring, and soil health.', amount: 'Varies', deadline: 'Check Local', link: 'https://dnr.alaska.gov/ag/ag_grants/specialty_crop_block_grant.htm' },
  { id: 'usa-az-water', name: 'Arizona Agriculture, Soil Health, and Water Efficiency Innovation Pilot', organization: 'AZ Water', country: 'USA', regions: ['Arizona'], isFederal: false, benefits: ['Drought Tolerance', 'Soil Health'], description: 'Strong fit if framed as water-focused soil health, reduced fertilizer input, and improved drought tolerance.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.azwater.gov/rural-programs/funding-and-grant-information' },
  { id: 'usa-ar-nps', name: 'Arkansas Title X Cost-Share', organization: 'Arkansas Agriculture', country: 'USA', regions: ['Arkansas'], isFederal: false, benefits: ['Fertilizer Reduction'], description: 'Frame as reducing nutrient runoff and improving water quality through a reduced-N BMP trial.', amount: 'Varies', deadline: 'Check Local', link: 'https://agriculture.arkansas.gov/natural-resources/water-management/nonpoint-source-management/?utm_source=chatgpt.com' },
  { id: 'usa-co-soil', name: 'Colorado Soil Health Program', organization: 'Colorado Dept Ag', country: 'USA', regions: ['Colorado'], isFederal: false, benefits: ['Soil Health', 'Drought Tolerance'], description: 'Frame as soil-health + water-resilience + climate adaptation.', amount: 'Varies', deadline: 'Check Local', link: 'https://ag.colorado.gov/soil-health?utm_source=chatgpt.com' },
  { id: 'usa-ct-climate', name: 'Climate Smart Agriculture Grant', organization: 'CT.gov', country: 'USA', regions: ['Connecticut'], isFederal: false, benefits: ['General', 'Soil Health'], description: 'Best for soil-health, energy, climate resilience, or on-farm demonstration equipment.', amount: 'Varies', deadline: 'Check Local', link: 'https://portal.ct.gov/doag/home/services/grants/farmers?utm_source=chatgpt.com' },
  { id: 'usa-de-nmp', name: 'Nutrient Management Plan Cost-Share', organization: 'Delaware Ag', country: 'USA', regions: ['Delaware'], isFederal: false, benefits: ['Nitrogen Uptake', 'Fertilizer Reduction'], description: 'Strong planning fit. Use funding for nutrient-management planning and reduced synthetic fertilizer strategy.', amount: 'Varies', deadline: 'Check Local', link: 'https://agriculture.delaware.gov/grants-loans/?utm_source=chatgpt.com' },
  { id: 'usa-fl-bmp', name: 'FDACS BMP Cost Share', organization: 'Florida Dept Ag', country: 'USA', regions: ['Florida'], isFederal: false, benefits: ['Fertilizer Reduction', 'Drought Tolerance'], description: 'Strong fit for nutrient management, precision fertilizer, fertigation, and water-use efficiency.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.fdacs.gov/Water/Agricultural-Water-Field-Services/Agricultural-Best-Management-Practices/BMP-Cost-Share-Program' },
  { id: 'usa-ga-319', name: 'Section 319 Cost-Share', organization: 'Georgia Soil and Water', country: 'USA', regions: ['Georgia'], isFederal: false, benefits: ['Fertilizer Reduction'], description: 'Frame as an impaired-watershed nutrient-loss reduction project.', amount: 'Varies', deadline: 'Check Local', link: 'https://gaswcc.georgia.gov/agricultural-conservation-programs' },
  { id: 'usa-hi-scbg', name: 'Hawaii Specialty Crop Block Grant', organization: 'Hawaii Dept Ag', country: 'USA', regions: ['Hawaii'], isFederal: false, benefits: ['Yield Improvement'], description: 'Best for specialty crop demonstrations: vegetables, fruit, nursery, and floriculture.', amount: 'Varies', deadline: 'Check Local', link: 'https://dab.hawaii.gov/add/scbgp/' },
  { id: 'usa-id-wqpa', name: 'Water Quality Program for Agriculture', organization: 'Idaho Soil and Water', country: 'USA', regions: ['Idaho'], isFederal: false, benefits: ['Soil Health', 'Drought Tolerance'], description: 'Good fit through local conservation districts for water-quality BMPs, nutrient management, error reduction, and soil health.', amount: 'Varies', deadline: 'Check Local', link: 'https://localnews8.com/news/2025/05/20/idaho-conservation-districts-encouraged-to-apply-for-wqpa-grants-for-projects-in-fy-2026/' },
  { id: 'usa-il-icover', name: 'I-COVER & Sustainable Ag Cost-Share', organization: 'Illinois Dept Ag', country: 'USA', regions: ['Illinois'], isFederal: false, benefits: ['Fertilizer Reduction', 'Soil Health'], description: 'Strong fit if paired with cover crops, no-till, nutrient management, or a reduced-N system.', amount: 'Varies', deadline: 'Check Local', link: 'https://agr.illinois.gov/resources/conservation.html' },
  { id: 'usa-in-cwi', name: 'Clean Water Indiana', organization: 'Indiana.gov', country: 'USA', regions: ['Indiana'], isFederal: false, benefits: ['Fertilizer Reduction', 'Soil Health'], description: 'Apply through local SWCD partners. Frame as reduced N loss, water-quality protection, and soil health.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.in.gov/isda/divisions/soil-conservation/clean-water-indiana/' },
  { id: 'usa-ks-cons', name: 'KDA Division of Conservation Cost-Share', organization: 'Kansas Dept Ag', country: 'USA', regions: ['Kansas'], isFederal: false, benefits: ['Fertilizer Reduction'], description: 'Frame as nutrient reduction, water quality, sediment/nutrient reduction, or riparian protection.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.agriculture.ks.gov/divisions-programs/division-of-conservation/financial-assistance' },
  { id: 'usa-ky-soil', name: 'Kentucky Soil Erosion & Water Quality Cost-Share', organization: 'Kentucky Energy/Env', country: 'USA', regions: ['Kentucky'], isFederal: false, benefits: ['Fertilizer Reduction', 'Soil Health'], description: 'Use the farm’s Ag Water Quality Plan and frame the project as erosion/water-quality/nutrient-loss reduction.', amount: 'Varies', deadline: 'Check Local', link: 'https://eec.ky.gov/Natural-Resources/Conservation/Pages/State-Cost-Share.aspx' },
  { id: 'usa-la-swcd', name: 'LDAF Office of Soil and Water Conservation', organization: 'Louisiana Ag', country: 'USA', regions: ['Louisiana'], isFederal: false, benefits: ['General'], description: 'For row crops, go through SWCDs and NRCS-style BMPs.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.ldaf.la.gov/about/organization/oswc' },
  { id: 'usa-me-soil', name: 'Maine Healthy Soils Program', organization: 'Maine', country: 'USA', regions: ['Maine'], isFederal: false, benefits: ['Soil Health', 'Drought Tolerance'], description: 'Frame as improving soil health, water retention, climate resilience, and nutrient-use efficiency.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.maine.gov/dacf/ard/resources/maine-healthy-soils-program.shtml' },
  { id: 'usa-md-macs', name: 'Maryland Ag Water Quality Cost-Share (MACS)', organization: 'Maryland.gov', country: 'USA', regions: ['Maryland'], isFederal: false, benefits: ['Fertilizer Reduction'], description: 'Strong fit for nutrient management and water-quality protection. Can cover up to 100% of eligible BMP costs.', amount: 'Varies', deadline: 'Check Local', link: 'https://mda.maryland.gov/resource_conservation/pages/macs.aspx' },
  { id: 'usa-ma-csap', name: 'Climate Smart Agriculture Program (CSAP)', organization: 'Mass.gov', country: 'USA', regions: ['Massachusetts'], isFederal: false, benefits: ['Soil Health'], description: 'Frame as soil-health, environmental improvement, energy/water efficiency, or climate resilient production.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.mass.gov/how-to/how-to-apply-to-the-climate-smart-agriculture-program' },
  { id: 'usa-mi-network', name: 'Regenerative Farmer Network Grant', organization: 'Michigan Dept Ag', country: 'USA', regions: ['Michigan'], isFederal: false, benefits: ['Fertilizer Reduction', 'Soil Health'], description: 'Best fit is a producer network or demonstration: reduced N, soil health, regenerative practices, and peer learning.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.michigan.gov/mdard/business-development/grantfund' },
  { id: 'usa-mn-agri', name: 'AGRI Sustainable Ag Demo Grant', organization: 'Mn Dept Ag', country: 'USA', regions: ['Minnesota'], isFederal: false, benefits: ['Fertilizer Reduction', 'Yield Improvement'], description: 'Strong demo fit. Use a replicated on-farm trial measuring profitability, N-use efficiency, and yield.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.mda.state.mn.us/business-dev-loans-grants/agri-sustainable-agriculture-demonstration-grant' },
  { id: 'usa-ms-swcc', name: 'MS Soil and Water Cost Share Program', organization: 'Mississippi SOS', country: 'USA', regions: ['Mississippi'], isFederal: false, benefits: ['Fertilizer Reduction', 'Soil Health'], description: 'Frame as soil/water conservation and nutrient-management BMP adoption through SWCD.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.sos.ms.gov/ACCode/00000299c.pdf' },
  { id: 'usa-mo-swcc', name: 'MO Soil and Water Cost-Share Program', organization: 'Missouri DNR', country: 'USA', regions: ['Missouri'], isFederal: false, benefits: ['Soil Health', 'Fertilizer Reduction'], description: 'Frame as reducing soil erosion, protecting water, improving soil health, and reducing nutrient losses. Reimburse up to 75%.', amount: 'Varies', deadline: 'Check Local', link: 'https://dnr.mo.gov/document-search/cost-share-program-pub0624/pub0624' },
  { id: 'usa-mt-gta', name: 'Growth Through Agriculture (GTA)', organization: 'Montana Dept Ag', country: 'USA', regions: ['Montana'], isFederal: false, benefits: ['General'], description: 'Better for commercialization or demonstration than pure input purchase. Good for demoing biostimulants.', amount: 'Varies', deadline: 'Check Local', link: 'https://agr.mt.gov/I-Want-To/Apply/Grants' },
  { id: 'usa-ne-niria', name: 'Nitrogen Reduction Incentive Program (NiRIA)', organization: 'DWEE NE', country: 'USA', regions: ['Nebraska'], isFederal: false, benefits: ['Fertilizer Reduction', 'Nitrogen Uptake'], description: 'Very strong direct fit. Nebraska’s program pays producers to reduce commercial fertilizer by 40 lb/ac or 15%.', amount: 'Incentive Payments', deadline: 'Check Local', link: 'https://dwee.nebraska.gov/news-events/press-releases/nebraska-extends-incentive-program-cut-fertilizer-use-2026-growing-season' },
  { id: 'usa-nv-scbg', name: 'Western SARE Nevada / SCBG', organization: 'Nevada Dept Ag', country: 'USA', regions: ['Nevada'], isFederal: false, benefits: ['Drought Tolerance'], description: 'Use SARE/NRCS for a drought-resilience or water-efficiency trial.', amount: 'Varies', deadline: 'Check Local', link: 'https://agri.nv.gov/Administration/Grant_Opportunities/' },
  { id: 'usa-nh-cc', name: 'NH Conservation Districts Climate Resilience', organization: 'NH CD', country: 'USA', regions: ['New Hampshire'], isFederal: false, benefits: ['Drought Tolerance', 'Soil Health'], description: 'Strong climate-resilience/demo fit via local conservation districts.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.sccdnh.org/climate-grant' },
  { id: 'usa-nj-ccs', name: 'NJ Ag Conservation Cost Sharing', organization: 'NJ.gov', country: 'USA', regions: ['New Jersey'], isFederal: false, benefits: ['Fertilizer Reduction'], description: 'Frame as soil erosion control, nutrient management, water quality, and nonpoint-source pollution reduction.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.nj.gov/agriculture/divisions/anr/agriassist/conservation.shtml' },
  { id: 'usa-nm-healthy', name: 'NMDA Healthy Soil Program', organization: 'NM Dept Ag', country: 'USA', regions: ['New Mexico'], isFederal: false, benefits: ['Soil Health', 'Yield Improvement'], description: 'Frame as increasing soil organic matter, water retention, and profitability under reduced fertilizer.', amount: 'Varies', deadline: 'Check Local', link: 'https://nmdeptag.nmsu.edu/healthy-soil-program.html' },
  { id: 'usa-nc-acsp', name: 'Agriculture Cost Share Program (ACSP)', organization: 'NC Ag', country: 'USA', regions: ['North Carolina'], isFederal: false, benefits: ['Fertilizer Reduction', 'Soil Health'], description: 'Strong fit for water-quality BMPs, runoff reduction, and nutrient management. Up to 75% cost-share.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.ncagr.gov/divisions/soil-water-conservation/programs-initiatives/ACSP' },
  { id: 'usa-nd-soil', name: 'Soil Health Cover Crop Grant', organization: 'ND Dept Ag', country: 'USA', regions: ['North Dakota'], isFederal: false, benefits: ['Soil Health'], description: 'Best state fit is soil-health/cover-crop integration with N reduction trials.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.ndda.nd.gov/news/applications-open-soil-health-cover-crop-grant-program-0' },
  { id: 'usa-oh-h20', name: 'H2Ohio', organization: 'Ohio H2O', country: 'USA', regions: ['Ohio'], isFederal: false, benefits: ['Fertilizer Reduction'], description: 'Very strong fit in priority watersheds. Frame as voluntary nutrient management and reduced fertilizer losses.', amount: 'Varies', deadline: 'Check Local', link: 'https://h2.ohio.gov/water-quality-projects/managing-nutrients' },
  { id: 'usa-ok-cons', name: 'OK Conservation Commission Cost-Share', organization: 'OK Cons', country: 'USA', regions: ['Oklahoma'], isFederal: false, benefits: ['Soil Health', 'Fertilizer Reduction'], description: 'Frame as improving water quality, controlling erosion, improving soil health, and reducing nutrient losses.', amount: 'Varies', deadline: 'Check Local', link: 'https://conservation.ok.gov/locally-led-cost-share-program/' },
  { id: 'usa-or-water', name: 'ODA Ag Water Quality Grants', organization: 'Oregon', country: 'USA', regions: ['Oregon'], isFederal: false, benefits: ['Fertilizer Reduction'], description: 'Good fit through a local SWCD or watershed council. Frame as water-quality or nutrient-loss reduction.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.oregon.gov/oda/natural-resources/agwq/pages/ag-wq-grants.aspx' },
  { id: 'usa-pa-acap', name: 'Agriculture Conservation Assistance (ACAP)', organization: 'PA CD', country: 'USA', regions: ['Pennsylvania'], isFederal: false, benefits: ['Fertilizer Reduction'], description: 'Frame as a nutrient-management BMP tied to a conservation/nutrient/manure plan.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.nccdpa.org/programs/the-agriculture-conservation-assistance-program-acap/' },
  { id: 'usa-ri-dem', name: 'RI DEM Ag Grants', organization: 'RI DEM', country: 'USA', regions: ['Rhode Island'], isFederal: false, benefits: ['Drought Tolerance'], description: 'Use SCBGP for specialty crops or partner with a conservation applicant for climate resilience.', amount: 'Varies', deadline: 'Check Local', link: 'https://dem.ri.gov/natural-resources-bureau/agriculture-and-forest-environment/agriculture/ag-business-development-grants' },
  { id: 'usa-sc-scbgp', name: 'SCDA Specialty Crop Block Grant', organization: 'South Carolina Dept Ag', country: 'USA', regions: ['South Carolina'], isFederal: false, benefits: ['Yield Improvement', 'Drought Tolerance'], description: 'Best for specialty crop growers. Frame as competitiveness through fertilizer reduction and drought resilience.', amount: 'Varies', deadline: 'Check Local', link: 'https://agriculture.sc.gov/wp-content/uploads/2026/01/SCBGP_RFA_2026.pdf' },
  { id: 'usa-sd-cons', name: 'South Dakota Conservation Grants', organization: 'SD Dept Ag', country: 'USA', regions: ['South Dakota'], isFederal: false, benefits: ['Soil Health', 'Drought Tolerance'], description: 'Use the local conservation district. Frame as soil health, water quality, nutrient management, or field demo.', amount: 'Varies', deadline: 'Check Local', link: 'https://danr.sd.gov/Conservation/Conservation/GrantsandLoans.aspx' },
  { id: 'usa-tn-arcf', name: 'Agricultural Resources Conservation Fund (ARCF)', organization: 'Tennessee Gov', country: 'USA', regions: ['Tennessee'], isFederal: false, benefits: ['Fertilizer Reduction'], description: 'Strong BMP route through county SWCD. ARCF supports BMPs that address resource concerns and improve water quality.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.tn.gov/content/dam/tn/agriculture/documents/landwaterstewardship/2026/FY%2027%20ARCF%20Guidance%20Revised%204.6.26v2-UA.pdf' },
  { id: 'usa-tx-wqmp', name: 'Texas TSSWCB WQMP Cost-Share', organization: 'Texas SWB', country: 'USA', regions: ['Texas'], isFederal: false, benefits: ['Fertilizer Reduction'], description: 'Strongest fit is a WQMP with nutrient-management BMPs and reduced fertilizer loss.', amount: 'Varies', deadline: 'Check Local', link: 'https://tsswcb.texas.gov/programs/water-quality-management-plan' },
  { id: 'usa-ut-agvip', name: 'Agricultural Voluntary Incentive Program (AgVIP)', organization: 'Utah Dept Ag', country: 'USA', regions: ['Utah'], isFederal: false, benefits: ['Fertilizer Reduction', 'Soil Health'], description: 'Very strong fit. AgVIP helps producers implement nutrient-management and soil-health practices.', amount: 'Varies', deadline: 'Check Local', link: 'https://ag.utah.gov/conservation/agricultural-voluntary-incentive-program/' },
  { id: 'usa-vt-fap', name: 'Farm Agronomic Practices (FAP)', organization: 'UVM', country: 'USA', regions: ['Vermont'], isFederal: false, benefits: ['Soil Health', 'Fertilizer Reduction'], description: 'Strong if tied to soil-based agronomic practices, crop production, or nutrient planning.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.uvm.edu/d10-files/documents/2025-09/UPDATED_9_2025_FundingOpportunities.pdf' },
  { id: 'usa-va-vacs', name: 'Virginia Ag BMP Cost-Share (VACS)', organization: 'VA DCR', country: 'USA', regions: ['Virginia'], isFederal: false, benefits: ['Fertilizer Reduction'], description: 'Very strong. Frame as nutrient-management planning, water quality, and reduced nutrient runoff.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.dcr.virginia.gov/costshare' },
  { id: 'usa-wa-sff-2', name: 'Sustainable Farms & Fields (SFF)', organization: 'WA Cons Comm', country: 'USA', regions: ['Washington'], isFederal: false, benefits: ['Soil Health'], description: 'Strong climate-smart fit. SFF funds practices that increase carbon sequestration.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.scc.wa.gov/programs/sustainable-farms-fields' },
  { id: 'usa-wv-agep', name: 'WV Agricultural Enhancement Program (AgEP)', organization: 'WVCA', country: 'USA', regions: ['West Virginia'], isFederal: false, benefits: ['Fertilizer Reduction'], description: 'Strong conservation-district route. Frame as voluntary BMP implementation for nutrient management.', amount: 'Varies', deadline: 'Check Local', link: 'https://www.wvca.us/AgEP.cfm' },
  { id: 'usa-wi-nopp', name: 'Commercial Nitrogen Optimization Pilot (NOPP)', organization: 'WI DATCP', country: 'USA', regions: ['Wisconsin'], isFederal: false, benefits: ['Fertilizer Reduction', 'Nitrogen Uptake'], description: 'One of the best options in the USA. NOPP funds projects to refine methods optimizing commercial nitrogen applications.', amount: 'Varies', deadline: 'Check Local', link: 'https://datcp.wi.gov/Pages/News_Media/2026NOPPGrantRecipients.aspx' },
  { id: 'usa-wy-water', name: 'Wyoming Water Quality Grant', organization: 'Wyoming Dept Ag', country: 'USA', regions: ['Wyoming'], isFederal: false, benefits: ['Fertilizer Reduction'], description: 'Best fit is water-quality or specialty-crop demo, rather than direct input subsidy.', amount: 'Varies', deadline: 'Check Local', link: 'https://agriculture.wy.gov/index.php?section=water-quality-grant' },
];

export const MOCK_GRANTS: Grant[] = RAW_GRANTS.map(grant => {
  const map: Record<string, Benefit> = {
    'Fertilizer Reduction': 'Nutrient & Fertilizer Management',
    'Nitrogen Uptake': 'Nutrient & Fertilizer Management',
    'Soil Health': 'Soil Health & Carbon',
    'Drought Tolerance': 'Climate & Drought Resilience',
    'Cold Resistance': 'Climate & Drought Resilience',
    'Yield Improvement': 'Crop Yield & Vigor',
    'Stand Improvement': 'Crop Yield & Vigor',
    'Germination': 'Crop Yield & Vigor',
    'General': 'On-Farm Trials & Research',
    'Expected': 'On-Farm Trials & Research'
  };

  const benefitsSet = new Set<Benefit>();
  for (const b of (grant.benefits || [])) {
    if (map[b]) benefitsSet.add(map[b]);
    else benefitsSet.add(b as Benefit);
  }

  const desc = (grant.description || '').toLowerCase();
  if (desc.includes('water') || desc.includes('runoff') || desc.includes('erosion')) {
    benefitsSet.add('Water Quality & Conservation');
  }
  if (desc.includes('specialty crop') || desc.includes('fruit') || desc.includes('vegetable')) {
    benefitsSet.add('Specialty Crops');
  }
  if (desc.includes('trial') || desc.includes('demo') || desc.includes('research')) {
    benefitsSet.add('On-Farm Trials & Research');
  }

  return {
    ...grant,
    benefits: Array.from(benefitsSet)
  };
});
